name: Deploy to Azure Web App - dining-service-4D

on:
  workflow_run:
    workflows: ["Build, Test, and Coverage Report - dining-service-4D"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build job (Node.js 18.x)
        uses: actions/download-artifact@v4
        with:
          name: node-app-18.x

      - name: Unzip artifact for deployment
        run: unzip release-18.x.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1F9A5E2A1BD0435D9CC830D81D8BCD58 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D66FC50C44BC41B39B6A18CBDDBEFCC1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4ADBCACD723349E3BDC05280B4467B51 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dining-service-4D'
          slot-name: 'Production'
          package: .
